# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeinboxCli < Formula
  desc "CodeInbox CLI."
  homepage "https://magicbell.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/codeinbox_Darwin_x86_64.tar.gz"
      sha256 "b2fb63554e219510b9ab59a4115c787e564d10fd61a7c4cf536c4a63eea13bb8"

      def install
        bin.install "codeinbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/codeinbox_Darwin_arm64.tar.gz"
      sha256 "132e586eb52b41b73eca324f4df70dabce04f7dfb77ba2407e5d88220d3b2bf0"

      def install
        bin.install "codeinbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/codeinbox_Linux_x86_64.tar.gz"
        sha256 "0011d073dd3f28befab8e71e0573540d7b7a9d738267c4a807b0023ba033b314"

        def install
          bin.install "codeinbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/codeinbox_Linux_arm64.tar.gz"
        sha256 "4bf26fa02dab554c4b8936ee83c8a2f07488e7e8ccc0bf132f27a93727deaaad"

        def install
          bin.install "codeinbox"
        end
      end
    end
  end
end
