# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeinbox < Formula
  desc "CodeInbox CLI."
  homepage "https://magicbell.com"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.2/codeinbox_Darwin_x86_64.tar.gz"
      sha256 "9f1b12542917101f28a2e7460d156a5f75206ab920543cef8be18249d788c323"

      def install
        bin.install "codeinbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.2/codeinbox_Darwin_arm64.tar.gz"
      sha256 "a58990fadf0f8a37e526edebf4ff66f9ecd04f32fb1ce07d8fa02e7aca4e0de8"

      def install
        bin.install "codeinbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.2/codeinbox_Linux_x86_64.tar.gz"
      sha256 "773999c7c6cbf28c7fe5c5bc7b0a3f9f654028ecf97df6aff84ce9d14c1b128f"
      def install
        bin.install "codeinbox"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.2/codeinbox_Linux_arm64.tar.gz"
      sha256 "b5723a8d2b71334207b980a56d56c8574e4d0967f07e1f8f2232d2e53db2d576"
      def install
        bin.install "codeinbox"
      end
    end
  end
end
