# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeinboxCli < Formula
  desc "CodeInbox CLI."
  homepage "https://magicbell.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/code-inbox/homebrew-tap/releases/download/v1.0.0/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "04218b19e99d9aa9af1a1b17240373b994a5e46c2e14feb046fca4f33ef66b75"

      def install
        bin.install "homebrew-tap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/code-inbox/homebrew-tap/releases/download/v1.0.0/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "2b2f1e8780e8952da0692189c5d0e0e47f93521c37698b5a10a5dd1bf7b51938"

      def install
        bin.install "homebrew-tap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/code-inbox/homebrew-tap/releases/download/v1.0.0/homebrew-tap_Linux_x86_64.tar.gz"
        sha256 "c9e140e58cd66a5a8c125857cfbd51c1996807f143790f82cdeb6ac9d448ce88"

        def install
          bin.install "homebrew-tap"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/code-inbox/homebrew-tap/releases/download/v1.0.0/homebrew-tap_Linux_arm64.tar.gz"
        sha256 "979dc18c9bd517a0eed0d62c122b6e48d43040680e2247122d7e602213eb8a50"

        def install
          bin.install "homebrew-tap"
        end
      end
    end
  end
end
