# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeinbox < Formula
  desc "CodeInbox CLI."
  homepage "https://magicbell.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/codeinbox_Darwin_x86_64.tar.gz"
      sha256 "bbec4e62f74836daa1632e6520e789e83a8fbea27b0affd442312898057485a9"

      def install
        bin.install "codeinbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/codeinbox_Darwin_arm64.tar.gz"
      sha256 "79bbe0d0cc25361fc237bcf9a28ef156bc9e54578ae3b34acbc3f6258a422c8a"

      def install
        bin.install "codeinbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/codeinbox_Linux_x86_64.tar.gz"
        sha256 "29b4d560febae630f66517532780c869e6e6fbfe82b7e67538b786c06dc70785"

        def install
          bin.install "codeinbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/codeinbox_Linux_arm64.tar.gz"
        sha256 "b5529ec072121ac08b5ad7e38c8497376163d253562f18383d5dbe8257c11fe4"

        def install
          bin.install "codeinbox"
        end
      end
    end
  end
end
