# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeinboxCli < Formula
  desc "CodeInbox CLI."
  homepage "https://magicbell.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "8105045ece114ee56496f429408277bfe768771ac12188866f57b9bf9f6307bb"

      def install
        bin.install "homebrew-tap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "d7097d96ff8195b528782e16fa156069836cbf7b78492a257a0282b5618afe9c"

      def install
        bin.install "homebrew-tap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/homebrew-tap_Linux_x86_64.tar.gz"
        sha256 "21829124e1f7923f2b8a68236a4ab96ebb88b4006d5517da951d3017ba1aafee"

        def install
          bin.install "homebrew-tap"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.0/homebrew-tap_Linux_arm64.tar.gz"
        sha256 "db474c9b1b996d379cb7164e893999c1b2a1c9295132f50f9dcb2f3e953e192f"

        def install
          bin.install "homebrew-tap"
        end
      end
    end
  end
end
