# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codeinbox < Formula
  desc "CodeInbox CLI."
  homepage "https://magicbell.com"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.1/codeinbox_Darwin_x86_64.tar.gz"
      sha256 "e03c25ef7b7495e8c9151c6c4b9900e51e1b41be5465141200a6617db3028964"

      def install
        bin.install "codeinbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.1/codeinbox_Darwin_arm64.tar.gz"
      sha256 "c6e1711bc600db9857d27759f41d779dad442911354d8103ef5c76c28344ae88"

      def install
        bin.install "codeinbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.1/codeinbox_Linux_x86_64.tar.gz"
        sha256 "5f95a071ab9d1fe5aa5cd19d333d732d21f8366000178292eb198ef85efe5b43"

        def install
          bin.install "codeinbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/codeinbox/homebrew-tap/releases/download/v1.0.1/codeinbox_Linux_arm64.tar.gz"
        sha256 "be8228525b44627542fec30666b3abc41cbe27626567e3aec8d0dd1f794072fb"

        def install
          bin.install "codeinbox"
        end
      end
    end
  end
end
